Repository gulyasgergely902/retroboard-v2, pull requests merged in 2025-07, with the labels that each got.

#1 Add vue3 frontend
  .github/workflows/docker_release.yml
  .gitignore
  README.md
  build_frontend.sh
  docker/Dockerfile
  frontend/.editorconfig
  frontend/.gitattributes
  frontend/.gitignore
  frontend/.prettierrc.json
  frontend/.vscode/extensions.json
  frontend/env.d.ts
  frontend/eslint.config.ts
  frontend/index.html
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/public/favicon.ico
  frontend/src/App.vue
  frontend/src/assets/base.css
  frontend/src/assets/logo.svg
  frontend/src/assets/main.css
  frontend/src/components/HelloWorld.vue
  frontend/src/components/TheWelcome.vue
  frontend/src/components/WelcomeItem.vue
  frontend/src/components/icons/IconCommunity.vue
  frontend/src/components/icons/IconDocumentation.vue
  frontend/src/components/icons/IconEcosystem.vue
  frontend/src/components/icons/IconSupport.vue
  frontend/src/components/icons/IconTooling.vue
  frontend/src/main.ts
  frontend/src/router/index.ts
  frontend/src/views/AboutView.vue
  frontend/src/views/HomeView.vue
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
  requirements.txt
  src/app/__init__.py
  src/app/database/models.py
  src/config.py
  src/run.py
Labels: feature

#10 Create homepage vue
  frontend/index.html
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/App.vue
  frontend/src/assets/base.css
  frontend/src/assets/main.css
  frontend/src/components/BoardCard.vue
  frontend/src/components/HelloWorld.vue
  frontend/src/components/MenuBar.vue
  frontend/src/components/TheWelcome.vue
  frontend/src/components/WelcomeItem.vue
  frontend/src/router/index.ts
  frontend/src/views/AboutView.vue
  frontend/src/views/BoardView.vue
  frontend/src/views/HomeView.vue
  frontend/vite.config.ts
Labels: ✨ feature

#11 [fix] Add proxy
  frontend/package.json
  frontend/vite.config.ts
Labels: 🚀 enhancement

#16 Frontend optimizations
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/BoardCard.vue
  frontend/src/components/FilterToggle.vue
  frontend/src/components/MenuBar.vue
  frontend/src/components/Toggle.vue
  frontend/src/composables/fetch.ts
  frontend/src/main.ts
  frontend/src/services/app/app.service.ts
  frontend/src/services/app/types.ts
  frontend/src/services/board/board.service.ts
  frontend/src/services/board/types.ts
  frontend/src/views/BoardView.vue
  frontend/src/views/HomeView.vue
Labels: 🚀 enhancement

#48 Input error design
  .vscode/settings.json
  frontend/src/assets/main.css
  frontend/src/components/BoardSettingsModal.vue
  frontend/src/components/NewBoardModal.vue
  frontend/src/components/NewNoteModal.vue
  frontend/src/components/YesNoModal.vue
  frontend/src/services/board/board.service.ts
  frontend/src/views/BoardView.vue
Labels: 🚀 enhancement

#50 Add initial categories on board creation
  backend/services/services.py
  frontend/src/assets/main.css
  frontend/src/components/NewBoardModal.vue
  frontend/src/services/app/app.service.ts
Labels: ✨ feature
